### ISSUE TITLE
Loading of javascript Mathjax.js  in  experiment

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#10]
i am using mathjax.js for equations .
 some times i get loading error(page does not load properly).
when i refresh the page and see again some times i get the equations ,some times not.
and also getting,
"math process error"  error at some places.

**Comment by ecthiender** [comment]
If you are getting page load errors, there is nothing much we can do about it. Maybe the internet/network is slow/down at that point of time.
That's why, when you refresh, sometimes the page loads fine.
The math process error must be happening because mathjax.js does not load, but your code still tries to execute some mathjax specific functions.

**Comment by ecthiender** [comment]
Have you downloaded a copy of mathjax.js and including the local version in your HTML, or are you hot-linking to their CDNs (like so: `<script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script>`) ?

**Comment by sranjanagi** [comment]
i am hot linking to their CDN.

**Comment by ecthiender** [comment]
Can you try dowloading a copy and including in your HTML, that way, even if
you have network issues mathjax will load from your local machine and your
lab application should work fine.
