### ISSUE TITLE
Linux Lab - issue with registering new user

### ISSUE THREAD

**Issue by geetabose** [Virtual-Labs/engineers-forum#14]
Dear Sir,
       Kindly make the following lab up and running:
 LINUX LAB. There is some issue in registering the new user on the login page. Kindly the needful urgently.

**Comment by apurv111** [comment]
Working on the fix. Hopefully, the issue will be resolved in a week or so.

**Comment by sanchita-dixit** [comment]
@apurv111 If this issue was resolved, please close this issue.

**Comment by sanchita-dixit** [comment]
@geetabose Since there is no reply on this issue, I am thereby closing the issue.

**Comment by ecthiender** [comment]
@sanchita-dixit why are you closing issues just because you have not received any reply?

**Comment by sanchita-dixit** [comment]
@anon I had a discussion on this with Geeta mam, and it was agreed upon
that if there is no reply from the issue creator for a week even after
being reminded of the same, then I can close the issue.

**Comment by barjatiyasaurabh** [comment]
I think we should not close bug reports just because of no response.  Bugs may take years to resolve.  Expecting users to resolve to bug issues within a week is not reasonable.

**Comment by ecthiender** [comment]
Absolutely! Agree 100%.  Maybe we can discuss with @geetabose and come up with a protocol to close issues (I think we should close issues only when they are resolved). Closing issues just because it is open for too long is not the solution. In fact it might mislead us. For example, this issue with Linux lab has not been solved yet, and closing this might mislead us into thinking that this issue does not exist anymore. And mindlessly commenting on issues, asking engineers to reply soon and closing them when they don't is not going to help us. 

This forum exists so that engineers can discuss different issues they are facing. I don't think our aim here is to have less number of open issues. We should strive to read each issue, query, question carefully and respond appropriately to them.

**Comment by ecthiender** [comment]
@apurv111 if this issues is not resolved, please re-open the issue. cc: @sanchita-dixit

**Comment by sanchita-dixit** [comment]
@apurv111 any updates on this issue?

**Comment by apurv111** [comment]
Still under progress.

On Wed, Sep 2, 2015 at 4:26 PM, sanchita-dixit <notifications@github.com>
wrote:

> @apurv111 <https://github.com/apurv111> any updates on this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Virtual-Labs/engineers-forum/issues/14#issuecomment-137029597>
> .
>



-- 
Apurv,
Project Engineer,
Virtual Labs Engineering and Architecture Division (VLEAD),
Vindhya B6-204, IIIT-H Campus,
Gachibowli, Hyderabad 500 032

**Comment by apurv111** [comment]
Khushpreet will be taking care of this lab from now on.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur As per apurv111 comments, he has recommended your name for taking over this issue. Any updates so far on the same?

**Comment by khushpreet-kaur** [comment]
@sanchita-dixit This issue has been assigned to @ayogi by Prof. Venkatesh Choppella last week. @ayogi Please comment.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur @ayogi @ashay-maheshwari This issue was assigned to Yogesh to work on. This is no longer a small issue as the entire linux lab would be redesigned by the assignee. Since Yogesh would also be leaving by 10th June, 2016, Ashay would be working on this lab. Since this issue about linux lab no longer provides any useful information and was created more than an year ago under different scenario, I am thereby closing this issue. Various developments on the Linux lab would be tracked in the Github repo : https://github.com/vlead/Linux-Lab. If in future we are required to refer to this issue, we can reopen it.
