### ISSUE TITLE
Hosting Request For Computer-Organization-IIITH Lab

### ISSUE THREAD

**Issue by apurv111** [Virtual-Labs/engineers-forum#16]
This lab is at level 5 and successfully tested with ADS.
The sources of the lab are versioned here:
https://github.com/Virtual-Labs/computer-organization-iiith
Please try to host the lab and let us know the url.

**Comment by apurv111** [comment]
Kindly update us with the progress of this issue.
In case the lab is already hosted, please let us know the URL.

**Comment by AmulyaSri** [comment]
Lab was already hosted and was taken down as we had an breach on Amazon.

**Comment by mzs-vlabs** [comment]
Dear Apurv, please refer to the spread sheet Soujanya has shared. This lab was hosted on AWS and was taken down due to recent breach.

AmulyaSri, can we update the landing page of this forum with the info that we are putting AWS migration until further notice?
So people can stay updated of the current progress.

**Comment by AmulyaSri** [comment]
Yeah, that would be better. Will do that.

**Comment by jayanthsagar** [comment]
Deployed.
please access the lab using http://cse11-iiith.vlabs.ac.in
