### ISSUE TITLE
Initial deployment of IIIT-H labs 

### ISSUE THREAD

**Issue by travula** [Virtual-Labs/engineers-forum#18]
We will put all the information here.

**Comment by soujanya123** [comment]
Here are the url's of the lab sources which were successfully tested over ADS:

https://github.com/Virtual-Labs/data-structures-iiith
https://github.com/Virtual-Labs/computer-programming-iiith
https://github.com/Virtual-Labs/digital-logic-design-iiith
https://github.com/Virtual-Labs/image-processing-iiith
https://github.com/Virtual-Labs/computer-graphics-iiith
https://github.com/Virtual-Labs/pattern-recognition-iiith
https://github.com/Virtual-Labs/electro-magnetic-theory-iiith
https://github.com/Virtual-Labs/cryptography-iiith
https://github.com/Virtual-Labs/artificial-neural-networks-iiith
https://github.com/Virtual-Labs/computer-organization-iiith
https://github.com/Virtual-Labs/vlsi-iiith

Please get them hosted and let us know the url.

**Comment by soujanya123** [comment]
I would like to mentioned that all these 11 lab sources have been updated recently, and I request you to take up the updated sources into consideration for hosting process disregards with the one's hosted earlier in December.

**Comment by sivashankerN** [comment]
Please provide us with updated labs and github urls which has to be redeploy on amazon.

**Comment by soujanya123** [comment]
Since we are not hosting any labs on amazon right now, I would request the VLEAD team to rehost the labs listed below on IIITH server as we wanted to have updated sources running. Here are the github url's of the 10 labs: 

https://github.com/Virtual-Labs/data-structures-iiith
https://github.com/Virtual-Labs/computer-programming-iiith
https://github.com/Virtual-Labs/digital-logic-design-iiith
https://github.com/Virtual-Labs/image-processing-iiith
https://github.com/Virtual-Labs/computer-graphics-iiith
https://github.com/Virtual-Labs/pattern-recognition-iiith
https://github.com/Virtual-Labs/cryptography-iiith
https://github.com/Virtual-Labs/artificial-neural-networks-iiith
https://github.com/Virtual-Labs/computer-organization-iiith
https://github.com/Virtual-Labs/vlsi-iiith

**Comment by jayanthsagar** [comment]
There are 11 IIITH labs, i remember 15 IIITH labs are ready on level5. can someone update this list.

**Comment by apurv111** [comment]
Here are the url's for remaining 5 labs:

https://github.com/Virtual-Labs/electro-magnetic-theory-iiith
https://github.com/Virtual-Labs/hydraulics-and-fluid-mechanics-iiith
https://github.com/Virtual-Labs/physical-sciences-iiith
https://github.com/Virtual-Labs/physical-chemistry-iiith
https://github.com/Virtual-Labs/basic-engineering-mechanics-and-strength-of-materials-iiith

**Comment by jayanthsagar** [comment]
deployed both on amazon(production) and base1(stagging)
