### ISSUE TITLE
Update existing lab: Population ecology Virtual Lab I : Amrita University

### ISSUE THREAD

**Issue by sreejithsr-amrita** [Virtual-Labs/engineers-forum#197]
Please update existing lab "Population ecology Virtual Lab I"  
from 
https://github.com/amritacreate/population-ecology-virtual-lab-i

**Comment by sanchita-dixit** [comment]
@sreejithsr-amrita Population Ecology Virtual Lab I was previously deployed with the github repo: https://github.com/amritacreate/population-ecology-virtual-lab-i-au
For updating the sources the URL given now is : https://github.com/amritacreate/population-ecology-virtual-lab-i
Should we go ahead with the current github repo url which you provided for updations?

**Comment by sreejithsr-amrita** [comment]
Hello,

We have discussed this with Geeta Bose yesterday, pls continue with update procedure from our repository.

**Comment by sanchita-dixit** [comment]
@sreejithsr-amrita @anishasl-create @amritacreate The hosting can't be done from your repository which is not under Virtual-Labs organisation. Various issues were raised regarding the access permissions for creation of repos under virtual-labs, but they are not being followed up from your side. Due to this, 2 lab hosting requests are pending for your institute. Please follow up these issues, so that we can resolve other issues dependent on these.

**Comment by sanchita-dixit** [comment]
@sreejithsr-amrita @anishasl-create @amritacreate The requested lab is re-hosted. Please follow the URL : http://pev-au.vlabs.ac.in/

**Comment by sanchita-dixit** [comment]
@sreejithsr-amrita @anishasl-create @amritacreate I am closing this issue as there are no further queries for the same and I hope the updated sources are working fine.
