### ISSUE TITLE
Hosting request for the updated content of micro-machining-laboratory-lab - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#223]
Please host the micro-machining lab.
Link is given below.

https://github.com/Virtual-Labs/micro-machining-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe We cannot host this lab with the updated sources now as this has been selected for the upcoming integration process of virtual labs workshop from 3-5 Feb, 2016 from the COEP labs hosted on production. The reason being that the already running version of this lab has already been tested by the VLEAD QA team and once we update it with the latest sources, all the defects raised by the VLEAD QA team would become invalid.
After some discussion, it was decided that we would host this lab with the updated sources during the workshop itself.

**Comment by sushilmedhe** [comment]
@sanchita-dixit I have updated the pre test and post test quiz. Now it is working fine. Can you please re-host this lab so I can check and solve if any issue is not resolved.

link is given below.
https://github.com/Virtual-Labs/micro-machining-laboratory-coep

**Comment by sushilmedhe** [comment]
@sanchita-dixit Please re-host this lab ASAP. its urgent.

link is given below.
https://github.com/Virtual-Labs/micro-machining-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe  Since this is one of the labs in the 10 labs listed for the QA to be undertaken by IIIT-H QA team, we would not be accepting any re-hosting requests without the QA process being followed for this lab. We cannot host it on production unless it is stamped approved from the QA team.The integration and QA process must be followed as per the workshop objectives (3rd-5th Feb, 2016) for this request.

**Comment by sushilmedhe** [comment]
We had problem with this lab during the presentation when Prof. Agashe was presenting lab. So can you host it urgently?

**Comment by sushilmedhe** [comment]
@sanchita-dixit This lab having issues with the pre test and post test. QA team had raised this issues for pre test, post test, back to experiment tab, simulator refresh button. I have solved pre test and post test issue. Once you will update the UI, the list of experiment will be given to user and simulator are working fine as I tried here as well I have shown to Suman mali. So almost all issues has been resolved. 

What can we do for the next process??
Should I change the labels for all issues and create release note then you will host the lab??
Help me out for this.

**Comment by varshanihanth** [comment]
@sushilmedhe  Kindly follow the [integration process](http://files.vlabs.ac.in/vlead-docs/integration-process.html) which has all the answers for you queries

**Comment by sushilmedhe** [comment]
@sanchita-dixit @kolliSuman  Please host this lab on QA server for QA team. I have resolved all the issues and released a release note in the same lab itself. Please re-host the lab.

link is given below.
https://github.com/Virtual-Labs/micro-machining-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe @varshanihanth I tried hosting this lab on QA environment for testing by QA team. But it is showing a blank screen. Since this problem is faced for few other labs as well, I did some debugging in the source code. It seems that content.html and default.html are working fine when running independently on browser. The problem seems to be in the index.html code. After debugging, it is showing error on line 63. Below is the snapshot attached for the same.

![debug-index html-file](https://cloud.githubusercontent.com/assets/13132618/13426048/0636efd6-dfd1-11e5-9dac-b7c73626d515.png)

I would recommend you to fix this bug in the file and also try this for other labs which are showing similar blank screens upon running in browser after putting in production.

**Comment by sushilmedhe** [comment]
@sanchita-dixit I was looking into the code for the bug. It seems that the working labs index.html and this micro machining labs index.html files are different. When you people have changed UI from 1.0 to 3.0 the index file must have been replaced. But in those labs which shows blank screen have the different code may be older one in index.html file as of working lab index file. That must be the issue in this case. For other labs the index.html file have replaced with new UI but this labs have the old index file. Check it out once. And tell to the person who have upgraded the UI.

**Comment by sanchita-dixit** [comment]
@sushilmedhe The person who has worked on this UI template conversion was an RA at VLEAD named Sonali. She is no longer working here. You have other labs working with the new UI. You can change the files of index.html by looking at the running labs.

**Comment by sushilmedhe** [comment]
@sanchita-dixit @khushpreet-kaur  I made changes in index.html file and some other contents too. Probably it will not show a blank screen. Kindly please re-host the lab ASAP so we can get the conclusion of the result. Once it is done I can go with the other labs. Kindly re-host this micromachining lab today itself on urgent basis.

link is given below.
https://github.com/Virtual-Labs/micro-machining-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe I have hosted the lab on QA environment for testing by QA for this lab. I verified the working of the above issues and it is now working fine. Once the QA team stamps it as approved for production, it would be hosted on production. You can raise the requests for re-hosting for all such labs now which had this blank screen issue due to UI template conversion. The URL for QA team is : http://mm-coep.base1.vlabs.ac.in/

**Comment by sushilmedhe** [comment]
@sanchita-dixit Please do re-hosting again this lab for QA team. As I found some linking problem with the lab for home page. I have made changes as well as added video tab. So re-host again for QA team. Otherwise it will show error for video tab and home index page link.

 link is given below.
https://github.com/Virtual-Labs/micro-machining-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The lab is re-hosted for QA team. Please follow the URL for QA : http://mm-coep.base1.vlabs.ac.in

**Comment by travula** [comment]
@sushilmedhe @vxc  @sanchita-dixit 
Sushil,
The lab has been hosted ans is accessed at http://mm-coep.vlabs.ac.in
