### ISSUE TITLE
Hosting request for the updated content of vibration-and-acoustics - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#226]
Please host the lab.
Link is given below.

https://github.com/Virtual-Labs/vibration-and-acoustics-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe We tried hosting the lab, but the latest sources are not working and showing just a blank white screen. There is no error message or any other message/prompt so that we can look into and try to resolve it. After much trials, we would recommend you to look into the source code as we are unable to find any problem from our side. We have reverted back to the already running version and the lab is accessible like before.

**Comment by sushilmedhe** [comment]
The lab is modified. Please host the lab.

https://github.com/Virtual-Labs/vibration-and-acoustics-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe We tried hosting the lab, but the latest sources are not working and showing a screen similar to below attached snapshot. After much trials, we would recommend you to look into the source code as we are unable to find any problem from our side. We have reverted back to the already running version and the lab is accessible like before. 
![virtual-acoustics lab](https://cloud.githubusercontent.com/assets/13132618/12714294/db3d1294-c8f9-11e5-8faf-0769e075737b.png)

**Comment by sushilmedhe** [comment]
@sanchita-dixit Have you tried to host this lab again? If not please try once and check it works properly or not. I have been working on code but I didn't found any issue as such. 
Please check.

**Comment by sanchita-dixit** [comment]
@sushilmedhe Yes I tried hosting it again. But it is still showing a blank screen.

**Comment by sanchita-dixit** [comment]
@sushilmedhe I have reverted back to the old sources where no modification to the content.html was made because latest sources were still showing a blank screen. Looking at the latest commits, I figured out that only the content.html page was modified. I have made changes in the code manually referring to the commits. Now the lab is working with the required changes made by you. This is a temporary solution to ensure correct content is available to the end users.

**Comment by sushilmedhe** [comment]
I have updated the UI 1.0 to 3.0. Please re-host the lab. 
link is given below

https://github.com/Virtual-Labs/vibration-and-acoustics-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The requested lab has been re-hosted. Please follow the URL : http://va-coep.vlabs.ac.in

**Comment by sushilmedhe** [comment]
@sanchita-dixit The lab is working fine. And UI 3.0 has been upgraded. Thanks
