### ISSUE TITLE
Request to host Chem engg lab

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#253]
I have made necessary changes in the repo, please host it again 
https://github.com/Virtual-Labs/chemical-engg-iitb

**Comment by sanchita-dixit** [comment]
@pushpdeep We would process this hosting request as of now since this lab is not listed in the 10 labs for which IIIT-H QA is responsible for testing. But we would recommend IIT-B to carry out the testing as per the integration-process guidelines. We would carry out the hosting of such labs till the proposed QA and integration process is approved and functional completely.

**Comment by sanchita-dixit** [comment]
@pushpdeep The requested lab has been re-hosted. Please follow the URL : http://ce-iitb.vlabs.ac.in/

**Comment by pushpdeep** [comment]
Thanks Sanchita
