### ISSUE TITLE
Hosting request of Micro-machining lab on QA environment for QA team - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#323]
The lab has been updated with the test cases as well as requirement document. I would like to request you, host the lab on QA environment for QA team to test the lab and requirement document as well.

Link is given below.
https://github.com/Virtual-Labs/micro-machining-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe Just a clarification, which is the QA team referred by you. Whether you want it to be hosted for QA testing by COEP or QA testing by IIIT-H QA team. Because there is no QA testing to be done from IIIT QA team. If you meant IIIT-H QA testing, then we can directly re-host this lab on production and QA testing has to be handled by the COEP team itself. IIIT-H no longer carries out QA testing for other labs.

**Comment by sushilmedhe** [comment]
@sanchita-dixit In that case host the lab on production as I have already tested lab working. Lab is working as per the test cases and the requirement document. Nihant was asking me for the requirement.org file before a month to test lab on QA environment, so I have done this. You can directly host the lab on production if it is so.

**Comment by sanchita-dixit** [comment]
@sushilmedhe Micro-machining lab has been re-hosted on production. Please follow the URL : http://mm-coep.vlabs.ac.in/
