### ISSUE TITLE
Request to re-host Computer Organization Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#335]
Please re-host Computer Organization Lab. (Need to give all permissions to /var/www to this lab)
Link to https://github.com/Virtual-Labs/computer-organization-iiith.git

Please deploy this lab for QA team to test it again on QA environment.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu I did not find this lab hosted on amazon as well as on IIIT-H server. In my opinion, this lab is not running on production due integration level issue. Please provide me with the lab id and running lab URL.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu @sadhanareddy @BSravanthi Please raise the issues with proper labels to avoid confusions from our end. For labs which are not hosted anywhere and are requested for hosting for the first time must be raised as : request to host XYZ lab with "request for hosting" label.

For labs which are already hosted and are requested for updation of sources due to changes/modifications in the code, must be raised as : request to re-host XYZ lab with "update lab sources" label.

Kindly follow the conventions to avoid confusions. Thanks

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The lab is indeed running on Amazon. Thank you for helping in pointing it out. The lab would be hosted on QA soon.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The Computer Organization Lab has been re-hosted on QA environment. But the UI is not what is expected. A screenshot is attached below with the current UI. You can follow the URL : http://cse11-iiith.base1.vlabs.ac.in . Please confirm whether the lab needs to be reverted back to the older version.

**Comment by sravanthimodepu** [comment]
@sanchita-dixit  Please revert back the lab to the older version, I will check the lab and let you know.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The labs has been reverted back to the older version and the URL remains the same as given above.

**Comment by sravanthimodepu** [comment]
@sanchita-dixit  Required changes are made, you can host the lab on QA environment for testing with the same URL.

**Comment by sravanthimodepu** [comment]
@sanchita-dixit gentle reminder.

**Comment by sravanthimodepu** [comment]
@sanchita-dixit Please deploy the lab on base1as soon as possible, as the lab is on hold for testing.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The lab is hosted on QA. Please follow the URL : http://cse11-iiith.base1.vlabs.ac.in
