### ISSUE TITLE
Containers are not reflecting proxy settings

### ISSUE THREAD

**Issue by pkjana** [Virtual-Labs/engineers-forum#41]
Hi,

We have set proxy in the host machine (/root/ovpl/config/config.json) as shown below

"ENVIRONMENT": {
        "HTTP_PROXY":"http://10.3.100.207:8080",
        "HTTPS_PROXY":"http://10.3.100.207:8080",
        "http_proxy":"http://10.3.100.207:8080",
        "https_proxy":"http://10.3.100.207:8080"
    },

However, the proxy settings are not reflected in the containers, as shown below:

[root@localhost src]# vzctl enter 5618
entered into CT 5618
root@test1234:/# echo $http_proxy

root@test1234:/# 

Kindly suggest how to copy the proxy settings automatically from the host system to the containers using ovpl. This is a work-stopper since no ubuntu packages get installed during the deployment process in the container, which causes the deployment to fail.

Regards,
Pabitra K Jana
IIT Kharagpur

**Comment by ecthiender** [comment]
Sorry for the delay in response. 

One possibility is, you can set the proxy inside the container as a part of your labspec.json?  Like before the steps to install the packages, you can mention: `export http_proxy="http://10.3.100.207:8080"` in your labspec.json.

But, remember to remove those lines from labspec.json when you push them to github, otherwise it won't work in other places.

Let us know if your issue got resolved.

**Comment by ecthiender** [comment]
@pkjana did you create the container manually or using ADS?

If you created the container using ADS, then ADS takes care of setting the proxies from the config.json. If you created the container manually then you have to set the proxies manually as well.

You can ignore my previous comment.

**Comment by sanchita-dixit** [comment]
@pkjana If the issue was resolved, kindly close the issue.

**Comment by sanchita-dixit** [comment]
@pkjana Since there is no reply on this issue, I am thereby closing this issue.
