### ISSUE TITLE
Hosting Request for Speech Signal Processing

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/engineers-forum#552]
## *Hosting Details*
*The Request will be deployed on the infrastructure requested through the latest on-boarding request. Please raise an updated on-boarding request if extra resources are required for this hosting request.*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab/Experiment) Name** : Speech Signal Processing
1. **Repo URL**: https://github.com/virtual-labs/speech-signal-processing-iiith
1. **Branch/Tag**: master/ v1.1.2
1. **Contact Person**: Sravanthi/Mrudhvika

## *Other Details*
No

**Comment by BalammaBoya** [comment]
## *Hosting Details*
*The Request will be deployed on the infrastructure requested through the latest on-boarding request. Please raise an updated on-boarding request if extra resources are required for this hosting request.*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab/Experiment) Name** : Speech Signal Processing
1. **Repo URL**:  https://github.com/virtual-labs/speech-signal-processing-iiith-js
1. **Branch/Tag**: master/ v1.1.1
1. **Contact Person**: Balamma
## *Other Details*

**Note: This host request source contains all  converted from **java/flash into javascript** experiments  and also fixed ui-3.0 theme issues.** 

1. This is a new [repo url](https://github.com/virtual-labs/speech-signal-processing-iiith-js) , so it's is different from previous host request [repo url](https://github.com/virtual-labs/speech-signal-processing-iiith) as we created new repo for experiments conversion from java/flash into javascript. 
2. This is new tag version (v1.1.1) as it's different from previous host request tag version (v1.1.2) because this new repo tag version started from initially.

**Comment by pavanchow** [comment]
@BalammaBoya 
Hosted the requested lab.
Hosted URL of Lab: https://ssp-iiith.vlabs.ac.in
Branch: Master
Tag: v1.1.1

Please check and confirm

**Comment by priya100raman** [comment]
Is analytics code instrumented ?

**Comment by pavanchow** [comment]
Yes, the analytics code is embedded in it.

**Comment by BalammaBoya** [comment]
The analytics code already existed, please check the following screen short, is it updated analytics code or not.

![Screenshot from 2020-09-30 09-05-23](https://user-images.githubusercontent.com/22425444/94640070-4275df00-02fb-11eb-9a5f-ccd6ab7f4dfd.png)

**Comment by BalammaBoya** [comment]
## *Hosting Details*
*The Request will be deployed on the infrastructure requested through the latest on-boarding request. Please raise an updated on-boarding request if extra resources are required for this hosting request.*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab/Experiment) Name** : Speech Signal Processing
1. **Repo URL**:  https://github.com/virtual-labs/speech-signal-processing-iiith-js
1. **Branch/Tag**: master/ v1.1.3
1. **Contact Person**: Balamma
## *Other Details*

**Note: This host request source contains all  converted from **java/flash into javascript** experiments  and also fixed ui-3.0 theme issues.**

**Comment by pavanchow** [comment]
@BalammaBoya
Hosted the requested lab.
Hosted URL of Lab: https://ssp-iiith.vlabs.ac.in
Branch: Master
Tag: v1.1.4

Please check and confirm

**Comment by BalammaBoya** [comment]
@pavanchow working fine hosted source. 

![Screenshot from 2020-10-22 16-35-23](https://user-images.githubusercontent.com/22425444/96862944-c5660180-1483-11eb-84ba-714bc812df94.png)

**Comment by pavanchow** [comment]
Duplicate. Please use issue https://github.com/virtual-labs/engineers-forum/issues/647 for Speech Signal Processing hosting-related issues.
