### ISSUE TITLE
Experiment Repository Creation Request for Microcontroller Lab

### ISSUE THREAD

**Issue by rajeevfee** [virtual-labs/engineers-forum#906]
## *Repository Creation Request*
Use this to get your experiment repository created or updated on GitHub under Virtual Labs organization.

1. #### Coordinating Institute: IIT Roorkee

2. #### Approver’s Name:  Dr R S Anand

3. #### Approved Proposal:[ ](https://drive.google.com/file/d/1wTYI4Z0XYkzCCuPL4jHglhBm1B2sa3e3/view?pli=1)

4. #### Hosted url: 

> 1.	Programming a binary Counter Using 8051 Microcontroller.
> 2.	Implementation of UP/DOWN counter using following input specification
> i.	Two General Purpose I/O Pins as Control Inputs,
> ii.	One Interrupt Pin as a Control Pin
> 
> 3.	Interface a DAC with 8051 Microcontroller and Generate a Ramp Output Through It.
> 4.	Interface an ADC with 8051 Microcontroller and Show the Corresponding Output in Two Seven Segment Displays.
> 5.	Design an 8-bit PN Sequence Generator Circuit Based on 8051 Microcontroller.

5. #### Primary GitHub Handle Details: 
Name: Dr RS Anand
GitHub Handle: [@anandfee](https://github.com/anandfee)
Email id: [anandfee@gmail.com](mailto:anandfee@gmail.com)

Name: Dr Tharun Reddy
GitHub Handle: tharuniitk
Email id: [tharun@iitk.ac.in](mailto:tharun@iitk.ac.in)

Name: Rajeev Kumar
GitHub Handle: [@rajeevfee](https://github.com/rajeevfee)
Email id: [rajeevkumar.rke@gmail.com](mailto:rajeevkumar.rke@gmail.com)

Name: Nipun Jain
GitHub Handle: [@jnipun1994](https://github.com/jnipun1994)
Email id: [nipunjain1305@gmail.com](mailto:nipunjain1305@gmail.com)

Name: Adarsh
GitHub Handle: adarshvp123
Email id: [adarshvp16@gmail.com](mailto:adarshvp16@gmail.com)

**Comment by ravikiran2020** [comment]
@rajeevfee Request you upload the Approved Proposal for the Microcontroller Lab.

**Comment by rajeevfee** [comment]
@ravikiran2020 [Approved Proposal](https://drive.google.com/file/d/1se9_OqNPnckyLlCA8Yj18GB2vn_NRpQb/view?usp=sharing)

**Comment by priya100raman** [comment]
@rajeevfee ,  This  seems to be a joint proposal between IITR and COEP.
COEP had already requested for exp repository creation for this lab. We have created the 5 experiments for this lab as per [this](https://github.com/virtual-labs/engineers-forum/issues/859) issue based the (not updated) proposal that they shared at that time. We assume that this will be one lab and not two separate labs. Let us know if this is not the case. Please confirm and we will send invites to IITR's remaining updated 5 experiments repos to the shared GitHub handles. We would like limit one Create Repository Request issue per lab and hence would like you to confirm before we send out the invites.  Also please let us know the Lab name ( COEP's lab name ( matches with the proposal) is different than yours) that so that we can maintain uniformity in the issue name.

**Comment by rajeevfee** [comment]
@priya100raman @ravikiran2020 
This is a combined proposal from COEP and IIT Roorkee (IITR), and you can consider it as a single lab. Please send invitations for the requested experimental repos and add the name of IITR as a coordinating Institute.

**Comment by priya100raman** [comment]
@rajeevfee, Also what will be the name of the lab ?

**Comment by rajeevfee** [comment]
@priya100raman @ravikiran2020 Lab Name  - Microcontroller Lab: Embedded System Design with 8051 and PIC
Microcontrollers

**Comment by ravikiran2020** [comment]
@rajeevfee We have sent invites from [Issue 882](https://github.com/virtual-labs/engineers-forum/issues/882) created by COEP.
Closing this issue the request already done by COEP.
